name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Update draft
        uses: release-drafter/release-drafter@3832cfb52f98ab0f0e5b62aecf94909e334d4da6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
