name: Validate

on:
  push:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: ⚙️ Enable Corepack
        run: corepack enable

      - name: ⚙️ Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: current
          cache: yarn

      - name: 📦 Install Dependencies
        run: NPQ_PKG_MGR=yarn npx npq install
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 🔍 Run Linter
        run: yarn lint

      - name: ✨ Check Formatting
        run: yarn format:check

      - name: 🧪 Run Tests
        run: yarn test
